### ISSUE TITLE
Using the react-sortable-tree in react 18

### ISSUE THREAD

**Issue by OrMeirchak** [frontend-collective/react-sortable-tree#940]
I recently updated the react version in the project I'm working on from "16.2.0" to "18.2.0". Since doing this I get the following errors:

uncaught error: unable to find node on an unmounted component
TypeError: this.clearMonitorSubscription is not a function.
the above error occurred in <scrolling(List)> component
Searching the internet shows that the "react-sortable-tree" library is no longer supported in react 18. And this is probably the reason for these errors.

Is there anyone who managed to work with the library in react 18?

**Comment by keshav100** [comment]
Same issue i am facing.
Unable to find any solution so I started to develop my own version.
Still, it is incomplete. https://github.com/keshavgautam/react-sortable-tree-by-keshav

**Comment by matin-mortazavi** [comment]
> I recently updated the react version in the project I'm working on from "16.2.0" to "18.2.0". Since doing this I get the following errors:
> 
> uncaught error: unable to find node on an unmounted component TypeError: this.clearMonitorSubscription is not a function. the above error occurred in <scrolling(List)> component
> 
> Searching the internet shows that the "react-sortable-tree" library is no longer supported in react 18. And this is probably the reason for these errors.
> 
> Is there anyone who managed to work with the library in react 18?

could u find any solution?

**Comment by gaeundev** [comment]
solution!

```jsx
<SortableTree
  {...props}
  isVirtualized={false}
/>
```

**Comment by NetanelElimelech** [comment]
@gaeundev Thank you! It works :)
